name: imgEnv
channels:
  - conda-forge
  - defaults
  - pytorch

dependencies:
  - python=3.7
  - pip
  - matplotlib
  - pytorch=1.12.1
  - torchvision
  - torchtext
  - opencv=4.6.0
  - jupyterlab
  - notebook
  

